services:
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      
  dotnet:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - CONNECTION_STRING=${CONNECTION_STRING}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
